#ifdef DAQ_MODE
    #include "daq_inter_obj.h"
    #include <string.h>
	std::string interface_config_file = "/home/petalinux/daq/InterfaceConfig";
	ToolFramework::DAQInterface DAQ_Inter(interface_config_file);


    slow_control_var_struct DAQ_chan_cmd_list[70] = {
    //LV SC Vars
        {OPTIONS_TYPE,CHAN_PARAM,6,"SET LV STATUS",NULL,NULL,NULL,NULL,{"ON","OFF"}},
        {OPTIONS_TYPE,CHAN_PARAM,6,"SET LV CPU MAIN",NULL,NULL,NULL,NULL,{"ON","OFF"}},
        {OPTIONS_TYPE,CHAN_PARAM,6,"SET LV CPU BACKUP",NULL,NULL,NULL,NULL,{"ON","OFF"}},
        {VARIABLE_TYPE,CHAN_PARAM,6,"SET LV VOLT",0,20,1,15},
        {VARIABLE_TYPE,CHAN_PARAM,6,"SET LV CURR",0,2500,100},

    // HV SC Vars
        {OPTIONS_TYPE,CHAN_PARAM,24, "SET HV STATUS",NULL,NULL,NULL,NULL,{"ON","OFF"}},
        {OPTIONS_TYPE,CHAN_PARAM,24, "SET HV CPU MAIN",NULL,NULL,NULL,NULL,{"ON","OFF"}},
        {OPTIONS_TYPE,CHAN_PARAM,24, "SET HV CPU BACKUP",NULL,NULL,NULL,NULL,{"ON","OFF"}},
        {VARIABLE_TYPE,CHAN_PARAM,24,"SET HV VOLT",0,2500,100,2500},
        {VARIABLE_TYPE,CHAN_PARAM,24,"SET HV CURR",0,500,50,500},
        {VARIABLE_TYPE,CHAN_PARAM,24,"SET HV RAMPUP",0,100,10,100},
        {VARIABLE_TYPE,CHAN_PARAM,24,"SET HV RAMPDOWN",0,100,10,100},
        {VARIABLE_TYPE,CHAN_PARAM,24,"SET HV TRIP",0,5,1,5}, // TODO

    // Digitizer 0 SC Vars
    // TODO
        {VARIABLE_TYPE,CHAN_PARAM,16,"SET DIG0 DISCTRES",2000,6000,100,4018},
        {VARIABLE_TYPE,CHAN_PARAM,16,"SET DIG0 INTTIME",0,100,50,5},
        {VARIABLE_TYPE,CHAN_PARAM,16,"SET DIG0 CALIB",0,100,50,5},
        {VARIABLE_TYPE,CHAN_PARAM,16,"SET DIG0 PEDTYPE",0,100,50,5},
        {VARIABLE_TYPE,CHAN_PARAM,16,"SET DIG0 DEADTIME",0,100,50,5},
        {VARIABLE_TYPE,ENV_PARAM,NULL,"SET DIG0 CALIBPWR",0,100,50,5},
        {VARIABLE_TYPE,ENV_PARAM,NULL,"SET DIG0 CALIBPULSE",0,100,50,5},
        {VARIABLE_TYPE,ENV_PARAM,NULL,"SET DIG0 CALIBLEN",0,100,50,5},
        {VARIABLE_TYPE,ENV_PARAM,NULL,"SET DIG0 CALIBAMP",0,100,50,5},
        {VARIABLE_TYPE,ENV_PARAM,NULL,"SET DIG0 CALIBPDN",0,100,50,5},
        {VARIABLE_TYPE,ENV_PARAM,NULL,"SET DIG0 CALIBMUTE",0,100,50,5},
        {VARIABLE_TYPE,ENV_PARAM,NULL,"SET DIG0 CALIBSEN",0,100,50,5},
        {VARIABLE_TYPE,ENV_PARAM,NULL,"SET DIG0 RMONT",0,100,50,5},
        {OPTIONS_TYPE,CHAN_PARAM,16,"SET DIG0 STATUS",NULL,NULL,NULL,NULL, {"ON","OFF"}},
        {OPTIONS_TYPE,CHAN_PARAM,16,"SET DIG0 FESTATUS",NULL,NULL,NULL,NULL, {"ON","OFF"}},
        {OPTIONS_TYPE,CHAN_PARAM,16,"SET DIG0 DAQSTATUS",NULL,NULL,NULL,NULL, {"ON","OFF"}},
        {OPTIONS_TYPE,CHAN_PARAM,16,"SET DIG0 ODSEL",NULL,NULL,NULL,NULL, {"0","1"}},
        {OPTIONS_TYPE,ENV_PARAM,NULL,"SET DIG0 CLOCK",NULL,NULL,NULL,NULL, {"DPB","LOCAL"}},
        {BUTTONS_TYPE,0,NULL,"SET DIG0 AURORARST",NULL,NULL,NULL,NULL,NULL},
        {BUTTONS_TYPE,0,NULL,"SET DIG0 TDCRST",NULL,NULL,NULL,NULL,NULL},
    // Digitizer 1 SC Vars
        // TODO
        {VARIABLE_TYPE,CHAN_PARAM,16,"SET DIG1 DISCTRES",2000,6000,100,4018},
        {VARIABLE_TYPE,CHAN_PARAM,16,"SET DIG1 INTTIME"},
        {VARIABLE_TYPE,CHAN_PARAM,16,"SET DIG1 CALIB"},
        {VARIABLE_TYPE,CHAN_PARAM,16,"SET DIG1 PEDTYPE"},
        {VARIABLE_TYPE,CHAN_PARAM,16,"SET DIG1 DEADTIME"},
        {VARIABLE_TYPE,ENV_PARAM,NULL,"SET DIG1 CALIBPWR"},
        {VARIABLE_TYPE,ENV_PARAM,NULL,"SET DIG1 CALIBPULSE"},
        {VARIABLE_TYPE,ENV_PARAM,NULL,"SET DIG1 CALIBLEN"},
        {VARIABLE_TYPE,ENV_PARAM,NULL,"SET DIG1 CALIBAMP"},
        {VARIABLE_TYPE,ENV_PARAM,NULL,"SET DIG1 CALIBPDN"},
        {VARIABLE_TYPE,ENV_PARAM,NULL,"SET DIG1 CALIBMUTE"},
        {VARIABLE_TYPE,ENV_PARAM,NULL,"SET DIG1 CALIBSEN"},
        {VARIABLE_TYPE,ENV_PARAM,NULL,"SET DIG1 RMONT"},
        {OPTIONS_TYPE,CHAN_PARAM,16,"SET DIG1 STATUS",NULL,NULL,NULL,NULL, {"ON","OFF"}},
        {OPTIONS_TYPE,CHAN_PARAM,16,"SET DIG1 FESTATUS",NULL,NULL,NULL,NULL, {"ON","OFF"}},
        {OPTIONS_TYPE,CHAN_PARAM,16,"SET DIG1 DAQSTATUS",NULL,NULL,NULL,NULL, {"ON","OFF"}},
        {OPTIONS_TYPE,CHAN_PARAM,16,"SET DIG1 ODSEL",NULL,NULL,NULL,NULL, {"0","1"}},
        {OPTIONS_TYPE,ENV_PARAM,NULL,"SET DIG1 CLOCK",NULL,NULL,NULL,NULL, {"DPB","LOCAL"}},
        {BUTTONS_TYPE,ENV_PARAM,NULL,"SET DIG1 AURORARST",NULL,NULL,NULL,NULL,NULL},
        {BUTTONS_TYPE,ENV_PARAM,NULL,"SET DIG1 TDCRST",NULL,NULL,NULL,NULL,NULL},

    //DPB Sc Vars
        {VARIABLE_TYPE,CHAN_PARAM,6,"SET DPB TEMP",-40,85,5,60},
        {VARIABLE_TYPE,CHAN_PARAM,6,"SET DPB CURR",100,300,20,160},
        {VARIABLE_TYPE,ENV_PARAM,NULL,"SET DPB TEMP PCB",0,70,10,50},
        {VARIABLE_TYPE,ENV_PARAM,NULL,"SET DPB TEMP FPGA",20,110,10,80},
        {VARIABLE_TYPE,ENV_PARAM,NULL,"SET DPB TEMP FPDCPU",20,110,10,80},
        {VARIABLE_TYPE,ENV_PARAM,NULL,"SET DPB TEMP LPDCPU",20,110,10,80},
        //{"SET DPB VOLT FPDCPU"},
        //{"SET DPB VOLT LPDCPU"},
        {VARIABLE_TYPE,ENV_PARAM,NULL,"SET DPB CURR 12V",400,3000,100,2200},
        {VARIABLE_TYPE,ENV_PARAM,NULL,"SET DPB CURR 3V3",400,3000,100,2200},
        {VARIABLE_TYPE,ENV_PARAM,NULL,"SET DPB CURR 1V8",400,3000,100,2200},
        {OPTIONS_TYPE,ENV_PARAM,NULL,"SET DPB STATUS SFP0",NULL,NULL,NULL,NULL, {"ON","OFF"}},
        {OPTIONS_TYPE,ENV_PARAM,NULL,"SET DPB STATUS SFP1",NULL,NULL,NULL,NULL, {"ON","OFF"}},
        {OPTIONS_TYPE,ENV_PARAM,NULL,"SET DPB STATUS SFP2",NULL,NULL,NULL,NULL, {"ON","OFF"}},
        {OPTIONS_TYPE,ENV_PARAM,NULL,"SET DPB STATUS SFP3",NULL,NULL,NULL,NULL, {"ON","OFF"}},
        {OPTIONS_TYPE,ENV_PARAM,NULL,"SET DPB STATUS SFP4",NULL,NULL,NULL,NULL, {"ON","OFF"}},
        {OPTIONS_TYPE,ENV_PARAM,NULL,"SET DPB STATUS SFP5",NULL,NULL,NULL,NULL,{"ON","OFF"}},
        {OPTIONS_TYPE,ENV_PARAM,NULL,"SET DPB STATUS ETH0",NULL,NULL,NULL,NULL, {"ON","OFF"}},
        {OPTIONS_TYPE,ENV_PARAM,NULL,"SET DPB STATUS ETH1",NULL,NULL,NULL,NULL, {"ON","OFF"}}
    };
#endif